# Generated by Django 5.1.5 on 2025-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_blog', '0002_post_category_post_views_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
