# Generated by Django 5.1.5 on 2025-01-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
